name: Siteops Lint

on:
  pull_request:
    paths:
      - '**'
      - '.github/workflows/**'
  push:
    branches: [main, master]
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  lint:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-go/.github/workflows/go-lint.yml@b253b2329a11552b6276781c56f6dc6fd1718710
    with:
      go-version: "1.25.8"
      working-directory: "."
