name: Stitcher Lint

on:
  pull_request:
    paths:
      - '**'
      - '.github/workflows/**'
  push:
    branches: [main, master]
    paths:
      - '**'
      - '.github/workflows/**'

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.8'
          cache: true
      - uses: golangci/golangci-lint-action@2f856675483cb8b9378ee77ee0beb67955aca9d7 # v6
        with:
          version: latest
          install-mode: goinstall
          skip-cache: true
          working-directory: .
